name: CI/CD Pipeline

on:
  push:
    branches:
      - main    
      - 'feature/*' 
  pull_request:
    branches:
      - main    
      - 'feature/*' 

jobs:
  code-quality:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: 'clear'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest

      - name: Code Formatting Check (Black)
        run: black --check .

      - name: Linting Check (Flake8)
        run: flake8 .

      - name: Run Tests
        run: pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t brankadi/epam_project:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push brankadi/epam_project:latest